/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void rcc_config(void);
void StartHSE(void);

int main(void)
{
	rcc_config();

    /* Loop forever */
	for(;;);
}

void rcc_config(void){
	StartHSE();
}

/**
 * Description: This function enables the interrupt on HSE ready,
 * and start the HSE as external clock.
 */
__INLINE void StartHSE(void)
{
	/* Configure NVIC for RCC */
	/* (1) Enable Interrupt on RCC */
	/* (2) Set priority for RCC */
	NVIC_EnableIRQ(RCC_CRS_IRQn); /* (1)*/
	NVIC_SetPriority(RCC_CRS_IRQn,0); /* (2) */

	/* (1) Enable interrupt on HSE ready */
	/* (2) Enable the CSS
	Enable the HSE and set HSEBYP to use the external clock
	instead of an oscillator
	Enable HSE */
	/* Note : the clock is switched to HSE in the RCC_CRS_IRQHandler ISR */
	RCC->CIR |= RCC_CIR_HSERDYIE; /* (1) */
	RCC->CR |= RCC_CR_CSSON | RCC_CR_HSEBYP | RCC_CR_HSEON; /* (2) */
}

/**
 * Description: This function handles RCC interrupt request
 * and switch the system clock to HSE.
 */
void RCC_CRS_IRQHandler(void)
{
	/* (1) Check the flag HSE ready */
	/* (2) Clear the flag HSE ready */
	/* (3) Switch the system clock to HSE */

	if ((RCC->CIR & RCC_CIR_HSERDYF) != 0) /* (1) */
	{
		RCC->CIR |= RCC_CIR_HSERDYC; /* (2) */
		RCC->CFGR = ((RCC->CFGR & (~RCC_CFGR_SW)) | RCC_CFGR_SW_0); /* (3) */
	}
	else
	{
		/* Report an error */
	}
}

